### ISSUE TITLE
Can’t Discover My New Flair Devices

### ISSUE THREAD

**Issue by noodleNT** [yracine/device-type.myFlair#1]
I have added two additional pucks and smart vents to Flair. When I try to update SmartThings to pull in the new devices, it doesn’t show any. It looks like the app needs a new auth token but I don’t see how to login agin.

**Comment by yracine** [comment]
Hi,

SmartThings has phased out the groovy platform, so my code will not work
anymore.  Refer to:

https://community.smartthings.com/t/the-end-of-groovy-has-arrived/246280

You're welcome to switch to Hubitat (you'd need a new hub) where my code is
still alive and kicking.

You'd need to contribute to the code as the UI & the storage of internal
variables are totally different .

https://community.hubitat.com/t/release-flair-devices-with-new-capabilities-for-building-physical-zones-in-your-home-and-controlling-your-mini-window-splits-portable-heaters-coolers/58228

Regards.
